/**
 * 理由碼常數(全案唯一來源)。
 * 介面文案一律繁體中文;理由碼一律引用此處英文常數,不得散落字串字面值。
 */
export const CODES = {
  // 政策決策
  POLICY_P1_PERMIT: 'POLICY_P1_PERMIT',
  POLICY_P2_CONFIDENTIAL: 'POLICY_P2_CONFIDENTIAL',
  CLAIM_NOT_IN_MANDATE: 'CLAIM_NOT_IN_MANDATE',

  // mandate 驗證
  MANDATE_REVOKED: 'MANDATE_REVOKED',
  MANDATE_EXPIRED: 'MANDATE_EXPIRED',
  MANDATE_SIG_INVALID: 'MANDATE_SIG_INVALID',
  DELEGATE_KEY_MISMATCH: 'DELEGATE_KEY_MISMATCH',
  QUERY_CAP_EXCEEDED: 'QUERY_CAP_EXCEEDED',

  // 重放防護
  REPLAY_DETECTED: 'REPLAY_DETECTED',

  // 憑證層
  CREDENTIAL_REVOKED: 'CREDENTIAL_REVOKED',
  CREDENTIAL_SIG_INVALID: 'CREDENTIAL_SIG_INVALID',
  VLEI_CHAIN_BROKEN: 'VLEI_CHAIN_BROKEN',

  // 幕 5 放行管線
  CARBON_OVER_THRESHOLD: 'CARBON_OVER_THRESHOLD',
  MULTI_SOURCE_CONFIRMED: 'MULTI_SOURCE_CONFIRMED',
  SINGLE_SOURCE_ONLY: 'SINGLE_SOURCE_ONLY',
  RELEASE_APPROVED: 'RELEASE_APPROVED',

  // 稽核
  AUDIT_CHAIN_TAMPERED: 'AUDIT_CHAIN_TAMPERED',
  DEPENDS_REVOKED: 'DEPENDS_REVOKED',
} as const;

export type ReasonCode = (typeof CODES)[keyof typeof CODES];
